version: '3.8'

services:
  db:
    image: postgres:16 
    container_name: time_tracking_pg
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: TimeTrackingDb
    ports:
      - "5455:5432"
    volumes:
      - pg_data_v2:/var/lib/postgresql/data

volumes:
  pg_data_v2: